# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gebug < Formula
  desc ""
  homepage "https://github.com/moshebe/gebug"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.3/gebug_1.0.3_Darwin_arm64.tar.gz"
      sha256 "c6114dc59f97d449cf8951159c0ab964a855a3c6869dc0106b5b968a2458e73a"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.3/gebug_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "7fdb7e0e7d28c8a348cd2f06f7a28722727eaef84ef4cd221eaa5ada6d43ae47"

      def install
        bin.install "gebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.3/gebug_1.0.3_Linux_arm64.tar.gz"
      sha256 "49118e06fed8a28b07338c826b3cdd57560d2d7c7c59a137d9e5a322db418846"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.3/gebug_1.0.3_Linux_x86_64.tar.gz"
      sha256 "f1acc29f123f5948350e8a695f955c14c4463651986ee70176cdd3b717972520"

      def install
        bin.install "gebug"
      end
    end
  end
end
