# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gebug < Formula
  desc ""
  homepage "https://github.com/moshebe/gebug"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.4/gebug_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "2fd116b990f949a81b5659a4cfd0583b7e3d118537a0d4b91c5a6130d55ed545"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.4/gebug_1.0.4_Darwin_arm64.tar.gz"
      sha256 "0adfce2fcf4e338eb1e7a39a3251097f9967e7ee4e62ccdb7131c95cd9f12467"

      def install
        bin.install "gebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.4/gebug_1.0.4_Linux_arm64.tar.gz"
      sha256 "dd7962da3c910b38506b12df05430942259ff0eb0a2ad055d211af7e14a282a4"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.4/gebug_1.0.4_Linux_x86_64.tar.gz"
      sha256 "1a1af3b0499f3eb9289f4b7ae56c630fff253fd9c27ecdd996b71bf74303c1d0"

      def install
        bin.install "gebug"
      end
    end
  end
end
