# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gebug < Formula
  desc ""
  homepage "https://github.com/moshebe/gebug"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.2/gebug_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "72a6b67c916e04d3766e0f508208653cdc9a86b9d02ea3d2e297b6daaa474245"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.2/gebug_1.0.2_Darwin_arm64.tar.gz"
      sha256 "f2e8b7ffcf7ef57d75676374c3935b9e3166e03b5d4eb26f3ae10d2161e84292"

      def install
        bin.install "gebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.2/gebug_1.0.2_Linux_arm64.tar.gz"
      sha256 "97ee1f39fa7f1d0b26eeec3ca0d05b68e9243193b15641ea1b8926484e444529"

      def install
        bin.install "gebug"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gebug/releases/download/v1.0.2/gebug_1.0.2_Linux_x86_64.tar.gz"
      sha256 "ffdb98b527843e3ec91fbab947eae42bd4bed58fbe2f03631e93644aa99e507f"

      def install
        bin.install "gebug"
      end
    end
  end
end
