# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtrace < Formula
  desc ""
  homepage "https://github.com/moshebe/gtrace"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.2/gtrace_1.0.2_Darwin_arm64.tar.gz"
      sha256 "10a5f87dbc5816ea911b6fda0282bdc533983f3455f96b9d37842bf63a023144"

      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.2/gtrace_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "9416121704522d9065cd5f80173630fb7f296d290fdd62b6b49126ffe7a5a48e"

      def install
        bin.install "gtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.2/gtrace_1.0.2_Linux_x86_64.tar.gz"
      sha256 "ccbe7a1ee01033af9a539ce2145a9a67b093b93b20dc7f4421932f438434086d"

      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.2/gtrace_1.0.2_Linux_arm64.tar.gz"
      sha256 "c72dacda022571632448732b17b28fca335abbbcade610a6b2400e1e84c17352"

      def install
        bin.install "gtrace"
      end
    end
  end
end
