# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtrace < Formula
  desc ""
  homepage "https://github.com/moshebe/gtrace"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.0/gtrace_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "02a1ec49f3804987aebfcd80c7599a9d4b3b4def715218b3c7388873f9fcf90c"

      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.0/gtrace_1.0.0_Darwin_arm64.tar.gz"
      sha256 "7e4313310c072440374bff2ace40eff60a4f7094b459954d83fa276f26270061"

      def install
        bin.install "gtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.0/gtrace_1.0.0_Linux_x86_64.tar.gz"
      sha256 "4189b51d040c34fe91f46c53dc5648d3e9ccfb0c8d172d4fba96734501589993"

      def install
        bin.install "gtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moshebe/gtrace/releases/download/v1.0.0/gtrace_1.0.0_Linux_arm64.tar.gz"
      sha256 "0eaf48ba02e73fb5f2baf0b37bde88be945b5c1fa0b7b82a34465c297090027b"

      def install
        bin.install "gtrace"
      end
    end
  end
end
